#Designing different levels
#'W' are walls, 'E' is the target object, 'D' is the Door
                               
levels = [[
"WWWWWWWWWWWWWWWWWWWWWWW",
"W            K        W",
"W    WW               W",
"W                     W",
"W           WWWWW     W",
"W                     W",
"W   WWW               W",
"W                     W",
"W           WWWWWWW   W",
"W                     W",
"WWWWWWWWW             W",
"W       D             W",
"WE      D             W",
"WWWWWWWWWWWWWWWWWWWWWWW",
],[
"WWWWWWWWWWWWWWWWWWWWWWW",
"W                     W",
"W                     W",
"WWWWWWWWWWWW          W",
"W             K       W",
"W                     W",
"W    WWWWWWWWWWWWWW   W",
"W    W   ED           W",
"W     WW  D           W",
"W       WWD           W",
"W       W     WWWWW   W",
"W                     W",
"W                     W",
"WWWWWWWWWWWWWWWWWWWWWWW",
],[
"WWWWWWWWWWWWWWWWWWWWWWW",
"W                     W",
"W                     W",
"W            WWWWWW   W",
"W                     W",
"W          K          W",
"WWWWWWWWWWWWWW        W",
"W            W        W",
"W           DW        W",
"W          DEW        W",
"W         WWWW        W",
"W                     W",
"W                     W",
"WWWWWWWWWWWWWWWWWWWWWWW",
]]